### ISSUE TITLE
Initial TODO list.

### ISSUE THREAD

**Issue by rturrado** [rturrado/TSReader#1]
- [X] Read elephants.ts and print out a summary of the TS packet PIDs (PID hex code, count, stream type, and stream description).
- [X] Parse adaptation field, adaptation extension, and payload data.
    Parsing of PSI (Program Specific Information) lets us know the PIDs for audio and video packets.
- [X] Write audio and video to output files.
    This is done as a post packet processing stage, together with the gathering of stats.
    These actions are optional, and requested by the user through command line parameters.
- [X] Revisit the PacketParser implementation: code more clear and elegant.
  - [X] Encapsulate basic repetitive operations (e.g. read from buffer and create bitset)
    - [ ] Implement the special case where the type is uint8_t?
  - [X] Simplify complex functions.
  - [ ] Read a whole section (a struct) with a single variadic templated function?
- [X] Revisit the PacketBuffer implementation: performance.
  - [X] Minimize the copy of vectors of bytes.
  - [X] Reimplement read operation as a get view returning a span.
- [X] CMake: add a CMakeLists.txt to compile the program in Windows and Linux.

**Comment by rturrado** [comment]
This list of tasks is going to be removed from the README file.
Adding it here just as for tracking purposes.
