### ISSUE TITLE
TODO list.

### ISSUE THREAD

**Issue by rturrado** [rturrado/TSReader#2]
- [ ] Test with other TS files than elephants.ts.
- [ ] New branch: reimplement using modules.
    This would be especially useful for Packet.h, since it is linked from many compilation units.
- [ ] New branch: reimplement the FileReader as a pipeline of stages (reading, parsing, processing, printing stats...)
- [ ] Add tests?
